name: CI

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing

jobs:
  arduino-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Arduino Tests
        run: |
          docker compose -f docker-compose-test.yml up --build arduino-test
          docker compose -f docker-compose-test.yml down

  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Go Tests
        run: |
          docker compose -f docker-compose-test.yml up --build --exit-code-from go-test go-test postgres
          docker compose -f docker-compose-test.yml down